# Generated by Django 5.1.2 on 2024-10-15 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantidade',
        ),
    ]
